---
- name: install and start the nginx
  hosts: web
  become: true
  gather_facts: false
  tasks:
    - name: installing nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes