---
- name: variables
  hosts: localhost
  become: true
  vars:
    course: "Ansibel"
    trainer: "SivaKumar"
    duration: "120 Hrs"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, we are learning {{course}} from {{trainer}}, duration is {{duration}}."