---
- name: vars passing through inventory file
  hosts: web
  become: true
  tasks:
    - name: passing vars
      ansible.builtin.debug:
        msg: "Hi, we are learning {{course}} from {{trainer}}, duration is {{duration}}."