---
- name: types of data types
  hosts: localhost
  become: true
  vars:
    course: Devops with aws #string
    Tools: #list or array
      - RHEL
      - shell
      - ansible
    experience: #dictionary or map(it consistes set of elements)
      devops:    #elements or number
      AWS: 5
      docker: 3
    male: true  #boolenan
    realproject: true
  tasks:
    - name: printing vars
      ansible.builtin.debug:
        msg: "In Course: {{course}} we covered {{Tools}} and experiance is {{experience}} is real project:{{realproject}}"
