---
- name: conditions
  hosts:  app
  become: yes
  tasks:
    - name: user exists or not
      ansible.builtin.command:  id azure-user

    - name: process continuied
      ansible.builtin.debug:
       msg: "process continuied"

