---
- name: conditions
  hosts:  app
  become: yes
  vars:
    user: "krishn"
  tasks:
    - name: user exists or not
      ansible.builtin.command: id {{user}}
      register: user_info
      ignore_errors: true

    - name: print user info
      ansible.builtin.debug:
       msg: "user info: {{user_info}}"
       
    - name: creating user
      when: user_info.rc != 0    #condition
      ansible.builtin.command: useradd {{user}}

