---
- name: conditions
  hosts:  40.83.167.39
  become: true
  tasks:
    - name: user exists or not
      ansible.builtin.debug:
        msg: "hellow"

    - name: process continuied
      ansible.builtin.debug:
       msg: "process continuied"

