---
- name: conditions
  hosts:  app
  become: true
  tasks:
    - name: user exists or not
      ansible.builtin.command: id root

    - name: process continuied
      ansible.builtin.debug:
       msg: "process continuied"

