---
- name: conditions
  hosts:  app
  become: yes
  tasks:
    - name: user exists or not
      ansible.builtin.command: id shivv
      register: user
      ignore_errors: true

    - name: print user info
      ansible.builtin.debug:
       msg: "user info: {{user}}"
       
    - name: create user
        ansible.builtin.command: useradd shivv
        when: user.rc != 0    #condition

