---
- name: check number from prompt
  hosts: localhost
  become: yes
  vars_prompt:
    - name: number
      prompt: Please enter number
      private: false
    
  tasks:
    - name: Number is less than 10
      when: number < 10
      ansible.builtin.debug:
        msg: "given number is less than 10"

    - name: number is grater than 10
      when: number > 10
      ansible.builtin.debug:
        msg: "given number is grater than 10"

